# Generated by Django 3.2.20 on 2023-08-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('STAFF', 'STAFF'), ('STUDENT', 'STUDENT')], default='ADMIN', max_length=100),
        ),
    ]
