# Generated by Django 3.2.20 on 2023-08-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_school_id_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school_id_no',
            new_name='school_id',
        ),
    ]
