# Generated by Django 3.2.20 on 2023-08-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_school_id_no_user_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('STAFF', 'STAFF'), ('STUDENT', 'STUDENT')], max_length=100),
        ),
    ]
