# Generated by Django 3.2.20 on 2023-08-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230806_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='item',
            new_name='activity',
        ),
        migrations.AddField(
            model_name='device',
            name='address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
