# Generated by Django 3.2.20 on 2023-08-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230808_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('CHECK IN', 'CHECK IN'), ('CHECK OUT', 'CHECK OUT')], default='CHECK IN', max_length=100),
        ),
    ]
