# Generated by Django 3.2.20 on 2023-07-18 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('BOOKS', 'BOOKS'), ('FILES', 'FILES'), ('WEB LINKS', 'WEB LINKS')], max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('file', models.FileField(null=True, upload_to='files')),
                ('link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, default=0)),
                ('featured', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
                ('created_bY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('liked_bY', models.ManyToManyField(related_name='book_likes', to=settings.AUTH_USER_MODEL)),
                ('updated_bY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_updates', to=settings.AUTH_USER_MODEL)),
                ('viewed_bY', models.ManyToManyField(related_name='book_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
    ]
